[phases.setup]
nixPkgs = [
    "nodejs_22",
    "glib",
    "nss",
    "nspr",
    "atk",
    "cups",
    "dbus",
    "libdrm",
    "libatasmart",
    "libxkbcommon",
    "pango",
    "cairo",
    "alsa-lib",
    "expat",
    "gtk3",
    "libgbm",
    "pciutils",
    "udev"
]

[phases.build]
cmds = ["npm install"]

[start]
cmd = "node índice.js"
