[phases.setup]
nixPkgs = [
    "nodejs_20",
    "glib",
    "nss",
    "nspr",
    "atk",
    "cups",
    "dbus",
    "libdrm",
    "libatasmart",
    "libxkbcommon",
    "pango",
    "cairo",
    "alsa-lib",
    "expat",
    "heimdal",
    "systemd",
    "libudev-zero",
    "mesa",
    "libgbm",
    "xdg-utils"
]
